remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

favicon: assets/favicon.ico

#title: "Free music demixer"
description: "AI-based music demixer running for free in your browser"
#description: "In music demixing, AI models are used to separate the different instruments from a music recording. This web application allows you to demix your own music files for free, and without having to install any software."
#tagline: kinda sucks

url: "https://freemusicdemixer.com"

author:
  name: "Sevag H"
  url: "https://sevag.xyz"

#logo - URL to a site-wide logo (e.g., /assets/your-company-logo.png) - If you would like the "publisher" property to be present, you must add this field to your site's configuration, during the validation of the structured data by Google Search Console, if the logo field is not validated, you will find errors inherent to the publisher in the Rich Results Testing Tool

social:
  name: Sevag H
  links:
    - https://github.com/sevagh
