remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-sitemap
  - jekyll-feed

favicon: assets/favicon.ico

# dont mess with SEO here
human_description: "AI-based music demixer running for free in your browser"
description: ""

url: "https://freemusicdemixer.com"

author: "sevagh"

#logo - URL to a site-wide logo (e.g., /assets/your-company-logo.png) - If you would like the "publisher" property to be present, you must add this field to your site's configuration, during the validation of the structured data by Google Search Console, if the logo field is not validated, you will find errors inherent to the publisher in the Rich Results Testing Tool

social:
  name: Sevag H
  links:
    - https://github.com/sevagh

google_analytics: 'G-B0BF5H94FM'
